### ISSUE TITLE
OneDScale / OneDScaleT no longer is displayed

### ISSUE THREAD

**Issue by madjens** [elicit-experiment/client-api#4]
When we run the script tests/Testcase_instrument2_stimuli.py and define OneDScale / OneDScaleT neither of the instruments are displayed regardless of stimuli configuration. 

![image](https://github.com/user-attachments/assets/da3f100d-601c-4cf1-a0a2-a68d72954b74)

**Comment by iainbryson** [comment]
This seems to work now, at least locally, on both Chrome and Firefox:

![image](https://github.com/user-attachments/assets/18f7651c-331b-474e-aca1-a8f11c41ce4a)

Does it still show up for you? If so, what browser/os?

**Comment by madjens** [comment]
I tried on Chrome and Edge on windows 10. It is still not showing the in either case

**Comment by iainbryson** [comment]
This should be fixed now. Verified using https://elicit-experiment.com/admin/studies/1119/protocols/1117

**Comment by madjens** [comment]
Yes the component is now displayed. However there are some visualization issues. Ill open another issue for that.
